server:
  port: 6085
spring:
  application:
    name: service-zuul
logging:
  config: classpath:logback.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6080/eureka/ #配置注册中心地址
zuul:
    routes:
        hiService :
            path : /hiService/**
            serviceId : service-hi
  

  
  
  
